name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - develop  # Set to your default branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Set to your Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          echo "$USERNAME@$HOST"
          ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST << 'EOF'
            cd /home/ubuntu/cosmos-backend  # Change to the directory of your app
            git checkout develop
            git pull origin develop  # Or use rsync/scp to copy files from the runner to your EC2 instance
            npm install --production  # Install any new dependencies
            pm2 restart all  # Or any other command to restart your app
          EOF
          rm -f deploy_key
