name: Deploy Node.js Application to EC2

on:
  push:
    branches:
      - actions  # Set to your default branch

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Set to a valid Node.js version

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_KEY" > deploy_key
          chmod 600 deploy_key
          ssh -o StrictHostKeyChecking=no -i deploy_key $USERNAME@$HOST << EOF
          cd /home/ubuntu/cosmos-backend/
          export NVM_DIR=~/.nvm
          source ~/.nvm/nvm.sh  
          git checkout actions
          git pull origin actions  
          npm install --production  
          pm2 restart all  
          exit
          EOF
          rm -f deploy_key
