name: Deploy

on:
  push:
    branches: [ develop ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            HOSTNAME: ${{secrets.HOST_DNS}}
            USER_NAME: ${{secrets.USERNAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

          cd /home/ubuntu/cosmos-backend &&
          sudo apt update
          git checkout develop &&
          git fetch --all &&
          git reset --hard origin/develop &&
          git pull origin develop &&
          npm i &&
          pm2 stop server.js &&
          pm2 start server.js
          '